export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "a holographic tiger in a futuristic cityscape, digital art",
  "a vintage record player playing music on a neon pink background, digital art",
  "a group of flamingos playing instruments in a jazz band, watercolor painting",
  "a futuristic city with flying cars and skyscrapers, 3D render",
  "a portrait of a person with cybernetic implants, oil painting",
  "a surreal landscape with floating islands and rainbow skies, digital art",
  "a giant squid attacking a pirate ship in a stormy sea, ink drawing",
  "a retro arcade with neon lights and classic games, 3D render",
  "a psychedelic mushroom forest with glowing colors, acrylic painting",
  "a cyberpunk street scene with neon lights and rain, 3D render",
  "an astronaut standing on a desolate planet, looking at a distant galaxy, digital art",
  "a dreamy landscape with a castle and floating islands, watercolor painting",
  "a steampunk airship flying over a Victorian city, digital art",
  "a group of mermaids singing and playing instruments under the sea, oil painting",
  "a dragon perched on a cliff overlooking a misty valley, graphite drawing",
  "a futuristic space station with glowing lights and sleek design, 3D render",
  "a unicorn in a rainbow-colored meadow, acrylic painting",
  "a cyberpunk city with towering buildings and flying vehicles, digital art",
  "a portrait of a person with intricate face tattoos, watercolor painting",
  "a surreal portrait of a person with a bird's head, oil painting",
  "a magical forest with glowing mushrooms and fireflies, digital art",
  "a retro-futuristic robot in a desert wasteland, 3D render",
  "a stormy seascape with a lighthouse and crashing waves, oil painting",
  "a dark fantasy landscape with a castle and ominous clouds, digital art",
  "a futuristic train speeding through a neon-lit city, 3D render",
  "a portrait of a person with glowing cybernetic eyes, digital art",
  "a cosmic landscape with swirling galaxies and bright stars, digital art",
  "a group of aliens playing music in a space bar, acrylic painting",
  "a post-apocalyptic wasteland with ruins and abandoned vehicles, 3D render",
  "a surreal portrait of a person with melting features, oil painting",
  "a magical underwater city with mermaids and sea creatures, digital art",
  "a steampunk robot with gears and pipes, ink drawing",
  "a retro-futuristic city with floating platforms and holographic ads, 3D render",
  "a portrait of a person with glowing tribal tattoos, acrylic painting",
  "a surreal landscape with melting objects and distorted perspectives, digital art",
  "a dystopian city with crumbling buildings and smoggy skies, 3D render",
  "a magical garden with giant flowers and whimsical creatures, watercolor painting",
  "a cyberpunk assassin with sleek black armor and glowing eyes, digital art",
  "a portrait of a person with an animal mask, oil painting",
  "a space battle with laser beams and explosions, 3D render",
  "a futuristic laboratory with glowing tubes and advanced technology, digital art",
  "a surreal portrait of a person with multiple faces, acrylic painting",
  "a fantasy landscape with floating islands and mythical creatures, digital art",
  "a retro-futuristic car with fins and chrome, ink drawing",
  "a cityscape with towering buildings and flying cars, digital art",
  "a portrait of a person with glowing neon hair, watercolor painting",
  "a cyberpunk hacker with a hood and glowing keyboard, digital art",
  "a cosmic horror landscape with tentacled monstrosities, digital art",
  "a surreal landscape with giant insects and strange flora, acrylic painting",
  "a futuristic stadium with holographic displays and robot players, 3D render",
  "a portrait of a person with glowing geometric tattoos, digital art",
  "a magical forest with a glowing portal to another realm",
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
];
